### ISSUE TITLE
Update userguide

### ISSUE THREAD

**Issue by AmroShohoud** [CS2103JAN2017-T15-B4/main#29]
change deadline to start/end
<[]|]|[]>

standardize tag argument

**Comment by Ellie-Peng** [comment]
Missing redo command features
See if you can make the command format easier to type.
The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
Suggested additions:
Add more pictures, make it more user friendly.
